name: build-openwrt-offical-dl

on: [push]
# hzez
# release:
#   types: published
# push:
#   branches:
#     - main
#   paths:
#     - 'Lean'
#   schedule:
#     - cron: 1 18 * * 1
#   watch:
#     types: started
  
env:
  REPO_URL:  https://github.com/openwrt/openwrt
  REPO_BRANCH: master
  CONFIG_FILE: config-x86-offical-hzez
  DIY_SH: diy-openwrt-offical.sh
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 初始环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
        
    - name: 下载源码
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt && cd openwrt
   
    - name: 导入自定义
      run: |
        git clone https://github.com/hzez/diy ./openwrt/diy/hzez
        mv ./openwrt/diy/hzez/$CONFIG_FILE $(pwd)
        mv ./openwrt/diy/hzez/$DIY_SH $(pwd)
        df -h && pwd
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_SH && cd openwrt && ../$DIY_SH
    - name: SSH连接
      uses: hzez/debugger-action@main
      if: env.SSH_ACTIONS == 'true'
        
    - name: 下载软件包
      id: package
      run: |
        cd openwrt && ./scripts/feeds clean && ./scripts/feeds update -a && ./scripts/feeds install -a && make oldconfig && make download -j8
        #cd openwrt && ./scripts/feeds clean && ./scripts/feeds update -a && ./scripts/feeds install -a && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: 固件编译
      id: compile
      run: |
        cd openwrt
        echo "::set-output name=status::success"
        echo "======================="
        cp -f .config ./dl/
        
    - name: 上传dl
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt-x86-Offical-dl
        path: openwrt/dl/.config

